editor: ensure NMACertChooser type is around
The widget classes templated with GtkBuilder don't load the types they
require, leaving their users in despair and gloom:

  ** (run-vpn:1094459): CRITICAL **: 11:33:54.424: file
        properties/nm-openvpn-editor.c: line 2623
        (openvpn_editor_new): should not be reached
  Error: .:4:2076 Invalid object type 'NMACertChooser'

Drag this one in manually.

https://gitlab.gnome.org/GNOME/NetworkManager-openvpn/merge_requests/11